#!/usr/bin/env python
"""
Copyright 2014 Wordnik, Inc.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
"""
class Account:
    """NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually."""


    def __init__(self):
        self.swaggerTypes = {
            'id': 'int',
            'type': 'str',
            'level': 'str',
            'password': 'str',
            'email': 'str',
            'partnerId': 'int',
            'proServiceId': 'int',
            'firstName': 'str',
            'useTimeout': 'bool',
            'timeoutMinutes': 'int',
            'lastName': 'str',
            'autoClassify': 'bool',
            'emailSuccess': 'bool',
            'emailFailure': 'bool',
            'emailCampaign': 'bool',
            'features': 'str',
            'releaseDestinations': 'list[str]',
            'plan': 'str',
            'addons': 'int',
            'pendingAddons': 'int',
            'pendingPlan': 'str',
            'renews': 'bool',
            'featuresAsMap': 'object',
            'addOnSourceConnectionQuota': 'int',
            'addOnStorageQuota': 'int',
            'brandingLogoUrl': 'str',
            'brandingName': 'str',
            'createdDate': 'date-time',
            'expiresDate': 'date-time',
            'partnerAccountId': 'str',
            'paymentDate': 'date-time',
            'pendingPlanSourceConnectionQuota': 'int',
            'pendingPlanStorageQuota': 'int',
            'priorClientIp': 'int',
            'priorLoginDate': 'int',
            'referralSourceConnectionQuota': 'int',
            'referralStorageQuota': 'int',
            'subscriptionSourceConnectionQuota': 'int',
            'subscriptionStorageQuota': 'int',
            'socialMediaUrl': 'str',
            'totalStorageQuota': 'int',
            'totalStorageUsage': 'int',
            'totalSourceConnectionQuota': 'int',
            'totalSourceConnectionUsage': 'int',
            'uploadEmail': 'str',
            'uploadUsername': 'str'

        }


        #Unique Id. Returned as a string. [RO]
        self.id = None # int
        #FileThis account type. [RO]
        self.type = None # str
        #FileThis account level. [RO]
        self.level = None # str
        #FileThis account password. [WO]
        self.password = None # str
        #User email (Also used for FileThis login).
        self.email = None # str
        #Unique Id of account's Content Delivery Partner. Returned as a string. [RO]
        self.partnerId = None # int
        #Unique Id of Pro-Service. [RO]
        self.proServiceId = None # int
        #User's first name
        self.firstName = None # str
        #Flag to enable/disable session timeout
        self.useTimeout = None # bool
        #Session timeout duration
        self.timeoutMinutes = None # int
        #User's last name
        self.lastName = None # str
        #Whether to automatically classify (tag) fetched documents, or not.
        self.autoClassify = None # bool
        #Send email when a fetch succeeds
        self.emailSuccess = None # bool
        #Send email when a fetch fails
        self.emailFailure = None # bool
        #Flag to subscribe/unsubscribe from marketing emails
        self.emailCampaign = None # bool
        #Internal FileThis feature flags. Base64-encoded. [RO]
        self.features = None # str
        self.releaseDestinations = None # list[str]
        #Subscription plan. [RO]
        self.plan = None # str
        #Number of 'add-on' packages purchased. [RO]
        self.addons = None # int
        #Number of 'add-on' packages upon renewal. [RO]
        self.pendingAddons = None # int
        #Subscription plan on renewal. [RO]
        self.pendingPlan = None # str
        #Does the account's subscription plan renew?. [RO]
        self.renews = None # bool
        self.featuresAsMap = None # object
        #Additional source connections from add-ons. [RO]
        self.addOnSourceConnectionQuota = None # int
        #Additional storage from add-ons in Kilobytes. [RO]
        self.addOnStorageQuota = None # int
        #Pro-Services branding logo. [RO]
        self.brandingLogoUrl = None # str
        #Pro-Services branding name. [RO]
        self.brandingName = None # str
        #Date created. [RO]
        self.createdDate = None # date-time
        #Date that the user's subscription plan expires. [RO]
        self.expiresDate = None # date-time
        #Unique Id given to account by Content Delivery Partner. [RO]
        self.partnerAccountId = None # str
        #Date payment made for subscription plan. [RO]
        self.paymentDate = None # date-time
        #Source connection quota for pending plan. [RO]
        self.pendingPlanSourceConnectionQuota = None # int
        #Storage quota for pending plan in Kilobytes. [RO]
        self.pendingPlanStorageQuota = None # int
        #IP address of user's previous login. [RO]
        self.priorClientIp = None # int
        #Date of user's previous login. [RO]
        self.priorLoginDate = None # int
        #Connection quota from referrals. [RO]
        self.referralSourceConnectionQuota = None # int
        #Storage quota from referrals in Kilobytes. [RO]
        self.referralStorageQuota = None # int
        #Connection quota from subscription. [RO]
        self.subscriptionSourceConnectionQuota = None # int
        #Storage quota from subscription in Kilobytes. [RO]
        self.subscriptionStorageQuota = None # int
        #Link for user to share FileThis. [RO]
        self.socialMediaUrl = None # str
        #Total storage quota for account in Kilobytes. [RO]
        self.totalStorageQuota = None # int
        #Total storage usage by account in Kilobytes. [RO]
        self.totalStorageUsage = None # int
        #Total source connection quota for account. [RO]
        self.totalSourceConnectionQuota = None # int
        #Total storage quota for account. [RO]
        self.totalSourceConnectionUsage = None # int
        #Upload email address [RO]
        self.uploadEmail = None # str
        #Upload user name
        self.uploadUsername = None # str
        
