#!/usr/bin/env python
"""
Copyright 2014 Wordnik, Inc.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
"""
class Destination:
    """NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually."""


    def __init__(self):
        self.swaggerTypes = {
            'name': 'str',
            'id': 'int',
            'state': 'str',
            'type': 'str',
            'provider': 'str',
            'logo': 'str',
            'url': 'str',
            'helpUrl': 'str',
            'iosAppId': 'str',
            'androidAppId': 'str',
            'appUrl': 'str',
            'ordinal': 'int',
            'logoUrl': 'str'

        }


        #Human-readable name of the destination. [RO]
        self.name = None # str
        #Unique Id for the destination. [RO]
        self.id = None # int
        #Whether the destination is exposed to the public or not. [RO]
        self.state = None # str
        #Type of destination (FileThis Cloud, external provider, or FileThis desktop). [RO]
        self.type = None # str
        #The storage provider. [RO]
        self.provider = None # str
        #Filename of provider's company logo. [RO]
        self.logo = None # str
        #Link to the provider's website. [RO]
        self.url = None # str
        #URL for FileThis help page that describes the destination. [RO]
        self.helpUrl = None # str
        #Application Id for iOS mobile app. [RO]
        self.iosAppId = None # str
        #Application Id for Android mobile app. [RO]
        self.androidAppId = None # str
        #Default web page for mobile app store. [RO]
        self.appUrl = None # str
        #An ordinal number that suggests a preferred order for display to users. [RO]
        self.ordinal = None # int
        #URL of destination's company logo. [RO]
        self.logoUrl = None # str
        
