#!/usr/bin/env python
"""
Copyright 2014 Wordnik, Inc.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
"""
class Document:
    """NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually."""


    def __init__(self):
        self.swaggerTypes = {
            'name': 'str',
            'id': 'int',
            'size': 'long',
            'shared': 'bool',
            'mimeType': 'str',
            'destinationId': 'int',
            'accountId': 'int',
            'pageCount': 'int',
            'kind': 'str',
            'deliveryState': 'str',
            'relevantDate': 'date-time',
            'actionDate': 'date-time',
            'createdDate': 'date-time',
            'addedDate': 'date-time',
            'deliveredDate': 'date-time',
            'originalName': 'str',
            'originalRelevantDate': 'date-time'

        }


        #Name of the document (default is typically its filename)
        self.name = None # str
        #Unique Id of the document. Returned as a string. [RO]
        self.id = None # int
        #Size of the document file in bytes. [RO]
        self.size = None # long
        #Whether this is a Pro-Services shared document, or not. [RO]
        self.shared = None # bool
        #MIME type of the document. [RO]
        self.mimeType = None # str
        #Unique Id of the destination to which the document was delivered. [RO]
        self.destinationId = None # int
        #Unique Id of document's account. Returned as a string. [RO]
        self.accountId = None # int
        #Number of pages in the document. [RO]
        self.pageCount = None # int
        #Kind of document. [RO]
        self.kind = None # str
        #Delivery state. [RO]
        self.deliveryState = None # str
        #Relevant date of document
        self.relevantDate = None # date-time
        #The date on which an action can be taken on a document (eg. Credit card payment due). [RO]
        self.actionDate = None # date-time
        #Date that the document was originally created. [RO]
        self.createdDate = None # date-time
        #Date that the document was added to FileThis. [RO]
        self.addedDate = None # date-time
        #Date the document was delivered to its destination. [RO]
        self.deliveredDate = None # date-time
        #The original name of the document (typically its filename). [RO]
        self.originalName = None # str
        #Relevant date determined by fetcher. [RO]
        self.originalRelevantDate = None # date-time
        
