#!/usr/bin/env python
"""
Copyright 2014 Wordnik, Inc.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
"""
class Institution:
    """NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually."""


    def __init__(self):
        self.swaggerTypes = {
            'name': 'str',
            'id': 'int',
            'state': 'str',
            'type': 'str',
            'info': 'str',
            'popularity': 'int',
            'homePageUrl': 'str',
            'phone': 'str',
            'logo': 'str',
            'fid': 'str',
            'logoUrl': 'str',
            'addedDate': 'date-time'

        }


        #Human-readable name of the source. [RO]
        self.name = None # str
        #The unique Id of the source. [RO]
        self.id = None # int
        #Whether the source is enabled for fetching, or not. [RO]
        self.state = None # str
        #The type of institution. [RO]
        self.type = None # str
        #A string to be displayed to users that gives special instructions. [RO]
        self.info = None # str
        #An integer representing the relative popularity of this source. [RO]
        self.popularity = None # int
        #Link for the home page of the source's website. [RO]
        self.homePageUrl = None # str
        #A phone number for the source institution. [RO]
        self.phone = None # str
        #Filename of institution's company logo. [RO]
        self.logo = None # str
        #The 'financial institution id' for the source. [RO]
        self.fid = None # str
        #URL of institution's company logo. [RO]
        self.logoUrl = None # str
        #Date that the source was added to FileThis. [RO]
        self.addedDate = None # date-time
        
